### ISSUE TITLE
Exif orientation support broken with Safari 13.1 (iOS and Desktop)

### ISSUE THREAD

**Issue by ssmithereens** [alextanhongpin/compress.js#11]
In Safari 13.1 (released a few days ago on iOS as part of iOS 13.4.1), the EXIF orientation value is no longer being handled properly, and the compressed image that is output will not have the correct orientation.

I believe that this change in Webkit (used by Safari) is the source of the problem: https://bugs.webkit.org/show_bug.cgi?id=201123

The required action for this library would be to ignore the EXIF orientation value when on Safari 13.1 (or later).

The easiest way to reproduce this is to go to the https://davidmoodie.com/client-compress/ demo site using a Safari or Chome browser on a device running iOS 13.4.1 and attempt to upload the attached image. This image has orientation EXIF value of 3 (rotated 180 degrees).

The demo page will return the image rendered upside down. However, the same image on a device not running iOS 13.4.1 will return the image rendered with the proper orientation.

![Demo-browser-on-iPhone-running-ios-13 4 1](https://user-images.githubusercontent.com/36458824/79051250-3424f100-7bfd-11ea-835e-bc037fa5fe24.jpeg)
![IMG_2119](https://user-images.githubusercontent.com/36458824/79051259-3dae5900-7bfd-11ea-9f67-3d458f6739c2.JPG)

**Comment by mberneis** [comment]
I encountered the same problem

**Comment by kacimfedjkhi** [comment]
Same problem here, mine rotates 90 degrees, any fix for this yet @alextanhongpin ? thanks!

**Comment by wujoho** [comment]
@alextanhongpin same issue here with iPhone Safari (iOS version 14.7.1), could you fix it please?
