### ISSUE TITLE
Error when running jest

### ISSUE THREAD

**Issue by leticiafontoura** [alextanhongpin/compress.js#15]
I'm getting an error when running jest

```
/node_modules/compress.js/src/index.js:2
    import "regenerator-runtime/runtime.js";
    ^^^^^^
SyntaxError: Cannot use import statement outside a module

import Compress from 'compress.js'
```

No idea what to do here.

**Comment by Puzzleton** [comment]
I'm running into the same issue, even on a fresh `create-react-app` project. Any support would be appreciated

**Comment by Kenneth-Fernandes-0620** [comment]
A workaround I have found is to use this library [React Image File Resizer](https://github.com/onurzorluer/react-image-file-resizer#readme) instead. It also has more activity and maintenance.
