### ISSUE TITLE
https://cdn.jsdelivr.net/gh/alextanhongpin/compress.js/build/index.js

### ISSUE THREAD

**Issue by MartijnHarmenzon** [alextanhongpin/compress.js#17]
Hi. Can it be that a new build created a problem with index.js?
We used it like this:

    <script
      src="https://cdn.jsdelivr.net/gh/alextanhongpin/compress.js/build/index.js"
      is:inline></script>
      
      const compress = new Compress();

**Comment by alextanhongpin** [comment]
You need to include `type="module"` in the script tag

**Comment by alextanhongpin** [comment]
See here
https://github.com/alextanhongpin/compress.js?tab=readme-ov-file#cdn

**Comment by MartijnHarmenzon** [comment]
Thanks @alextanhongpin. We will have a look.
