### ISSUE TITLE
Why you use jpeg ?

### ISSUE THREAD

**Issue by Themandunord** [alextanhongpin/compress.js#2]
Hi @alextanhongpin,

I want to know why you use exclusively the jpeg format to output the image ?
Why not png ?

It is possible to add param to custom that ? 

Thanks.

**Comment by alextanhongpin** [comment]
Hi @Themandunord, 

Thanks for noticing that. :smile:. 
I've included an additional param so that you can customize the output now.

**Comment by Themandunord** [comment]
Thanks !

But I see one more issue.

If I upload a gif, the base64 is not a gif anymore. And the image don't move anymore.
Do you see the problem ?

**Comment by alextanhongpin** [comment]
Hi @Themandunord,

Yes, I notice that the animation will be gone for images with the extension image/gif.

At the moment, I'll add a side note at the README.md to inform about this problem. I'll research on this issue now.

**Comment by Themandunord** [comment]
@alextanhongpin For help, I use that : 

```
function getBase64(img, callback) {
    const reader = new FileReader();
    reader.addEventListener('load', () => callback(reader.result));
    reader.readAsDataURL(img);
}
```

So the base64 image still move.

But I see that you convert your canvas to jpeg, so I think the problem come from here

**Comment by Themandunord** [comment]
`const base64 = canvas.toDataURL('image/jpeg', quality)` breaks the gif

**Comment by alextanhongpin** [comment]
According to the document here from [Mozilla Developer](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL), 

`var fullQuality = canvas.toDataURL("image/jpeg", 1.0);`

> A Number between 0 and 1 indicating image quality if the requested type is image/jpeg or image/webp.
If this argument is anything else, the default value for image quality is used. The default value is 0.92. Other arguments are ignored.

It seems like I can only compress the image if they are of type image/jpeg or image/webp.

**Comment by Themandunord** [comment]
You're right :/

image/webp can be animated, but only chrome supported this format.

**Comment by alextanhongpin** [comment]
:) I believe in near future the support for other images will be better.

**Comment by alextanhongpin** [comment]
If this is no longer an issue, can you close it?
