### ISSUE TITLE
Rotate image on loading from mobile devices.

### ISSUE THREAD

**Issue by DrBoria** [alextanhongpin/compress.js#4]
I tried to load image from android/ios devices on chrome/safari browser. And it rotate to horizontal orientation all images (from vertical turn to 90°).

**Comment by alextanhongpin** [comment]
Were the images uploaded from iOS/Android?

**Comment by DrBoria** [comment]
Both. Android and iOS.

**Comment by alextanhongpin** [comment]
Yup. Apologize for the delay. I have added a fix for it.

**Comment by DrBoria** [comment]
Cool, fixed, thanks!)
