### ISSUE TITLE
Make it clearer that units are decimal multiples of bytes

### ISSUE THREAD

**Issue by davejm** [alextanhongpin/compress.js#7]
https://github.com/alextanhongpin/compress.js/blob/881f1991f96bbbe5e870b8a16687cb4a4e7b106b/src/core/converter.js#L93-L94

~I think the number here should be 1024 rather than 1000 otherwise it's a bit misleading.~

**Comment by davejm** [comment]
It seems I was a bit naive with this view.. it's a bit more convoluted. In short, I think sticking with 1000 is correct but making it clear that these are the decimal definitions by using the correct units (kB/MB) and stating they are multiples of 1000 would aide confusion. Either that or the config takes bytes to stop confusion.

https://en.wikipedia.org/wiki/Kilobyte

**Comment by alextanhongpin** [comment]
I used to believe I had to divide it 1024 too, but the results I got showed otherwise.

Noted anyways :)
