### ISSUE TITLE
File size from base64 calculation

### ISSUE THREAD

**Issue by davejm** [alextanhongpin/compress.js#8]
Out of interest, how did you come up with this calculation? @alextanhongpin 

https://github.com/alextanhongpin/compress.js/blob/881f1991f96bbbe5e870b8a16687cb4a4e7b106b/src/core/base64.js#L3

**Comment by alextanhongpin** [comment]
Well, initially I thought that the size in base64 is supposed to be 4/3 times the original length, but then I came across this: https://en.wikipedia.org/wiki/Base64


> Very roughly, the final size of Base64-encoded binary data is equal to 1.37 times the original data size + 814 bytes (for headers). The size of the decoded data can be approximated with this formula:

```
bytes = (string_length(encoded_string) - 814) / 1.37
```

**Comment by davejm** [comment]
Interesting. Thanks!
